Repository KGU-2025-Capstone/K_Medi_Guide_AI, pull requests merged in 2025-05, with the labels that each got.

#16 [#15] feat : AI 모델 수정
  app.py
  config.py
  routes/detail.py
  routes/name.py
  routes/select.py
  routes/start.py
  routes/symptom.py
  services/gpt_fallback.py
  services/gpt_service.py
  services/session_store.py
  services/utils.py
Labels: enhancement

#20 [#19] refactor : candidate 내용 수정
  routes/name.py
  routes/symptom.py
Labels: refactor

#22 [#21] refactor : 증상 추출 로직 수정
  routes/name.py
  routes/start.py
  routes/symptom.py
Labels: refactor

#24 [#23] fix : name.py 오류 수정
  routes/name.py
Labels: bug

#25 Develop
  .gitignore
  README.md
  app.py
  config.py
  requirements.txt
  routes/__init__.py
  routes/detail.py
  routes/name.py
  routes/select.py
  routes/start.py
  routes/symptom.py
  services/__init__.py
  services/gpt_fallback.py
  services/gpt_service.py
  services/utils.py
  swagger.yaml
Labels: enhancement
